name: Build APK

on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: "17"

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - run: flutter config --no-analytics

      - run: yes | flutter doctor --android-licenses

      - run: flutter pub get

      - run: flutter build apk --debug -t lib/main_development.dart --flavor production

      - uses: actions/upload-artifact@v4
        with:
          name: socialgram-apk
          path: build/app/outputs/flutter-apk/app-production-debug.apk