-- ============================================================================
-- SocialGram Supabase Database Schema
-- Made by RWAGENCY
--
-- The complete, single-file database schema has been moved to:
--   supabase/complete_schema.sql
--
-- Run that file in the Supabase SQL Editor for a complete database setup
-- including all tables, indexes, policies, triggers, and admin features.
-- ============================================================================
